# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cab56b1b497739251794c457f5d2914f"
name = "sigmas"
handle = "sigmas"
application_url = "https://proceed-longitude-minus-transaction.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "finbarcustom.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_order_edits,read_orders,read_products,write_orders"

[auth]
redirect_urls = [
  "https://proceed-longitude-minus-transaction.trycloudflare.com/auth/callback",
  "https://proceed-longitude-minus-transaction.trycloudflare.com/auth/shopify/callback",
  "https://proceed-longitude-minus-transaction.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
